### PR TITLE
Add bounceHeight prop to loading animation

### PR DESCRIPTION
**Pull request by Watersdr**
This PR adds a property to control the bounce height of the dot animation.

I really want to use this component inside one of the buttons in our app but the animation is just too tall. With this prop, it will allow the consumer to adjust how high the dots animate.

Thanks!

### CODE REVIEW

**Review by persieahmad — APPROVED** [review]

**Comment by persieahmad** [comment]
@alexvcasillas 
Please merge this branch.

**Comment by alexvcasillas** [comment]
Hey, thank you so much for the PR, I'm sorry I didn't have the time enough to take a look at it until now.

**Comment by alexvcasillas** [comment]
Hey just wanted to let you know that the package is now available with your changes in version 1.2.0 at NPM https://www.npmjs.com/package/react-native-loading-dots

**Comment by Watersdr** [comment]
@alexvcasillas Awesome! Thanks for adding that 💪

**Comment by persieahmad** [comment]
Thank you @alexvcasillas and @Watersdr

**Pull request merged**
